version: '3'
services:
  flask-nginx-ui:
    container_name: flask-nginx-ui
    build: .
    image: flask-nginx-ui:latest
    ports:
      - "8080:8080"
    volumes:
      - nginx:/etc/nginx
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    container_name: nginx
    image: nginx:alpine3.19
    ports:
      - "443:443"
    volumes:
      - nginx:/etc/nginx

volumes:
  nginx: